service: crowdcall-server 

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1
  stage: dev

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true

